; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 3 (AST_INLINE_ASM = 15)
; Declaration 1 type: 2 (AST_INLINE_ASM = 15)
    ; Struct declaration: Vector3
    ; Struct Vector3: size=12, alignment=4

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    sub rsp, 416    ; Allocate 416 bytes on stack (aligned)
    ; Zero-initialize local variable space
    mov rdi, rsp  ; Destination for memset
    mov rax, 0     ; Value to set (zero)
    mov rcx, 416    ; Number of bytes
    rep stosb         ; Zero-fill the stack space
    ; Registering 0 function parameters
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
ir_entry_0:
    ; IR new: Vector3 (8 bytes)
    mov rcx, 8
    extern gc_alloc
    call gc_alloc
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    ; Store to variable: v1
    mov [rbp - 8], rax  ; To stack [rbp - 8]
    ; Load variable: v1
    mov rax, [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 0
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, 10
    mov rcx, rax
    pop rax
    mov dword [rax], ecx
    ; Load variable: v1
    mov rax, [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 4
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    push rax
    mov rax, 20
    mov rcx, rax
    pop rax
    mov dword [rax], ecx
    ; IR new: Vector3 (8 bytes)
    mov rcx, 8
    extern gc_alloc
    call gc_alloc
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    ; Store to variable: v2
    mov [rbp - 24], rax  ; To stack [rbp - 24]
    ; Load variable: v2
    mov rax, [rbp - 24]  ; From stack [rbp - 24]
    push rax
    mov rax, 8
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 136], rax
    mov rax, [rbp - 136]
    push rax
    mov rax, 30
    mov rcx, rax
    pop rax
    mov dword [rax], ecx
    ; Load variable: v1
    mov rax, [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 0
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 168], rax
    mov rax, [rbp - 168]
    mov eax, dword [rax]
    mov [rbp - 184], rax
    ; Load variable: v1
    mov rax, [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 4
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 200], rax
    mov rax, [rbp - 200]
    mov eax, dword [rax]
    mov [rbp - 216], rax
    mov rax, [rbp - 184]
    push rax
    mov rax, [rbp - 216]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 232], rax
    ; Load variable: v2
    mov rax, [rbp - 24]  ; From stack [rbp - 24]
    push rax
    mov rax, 8
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 248], rax
    mov rax, [rbp - 248]
    mov eax, dword [rax]
    mov [rbp - 264], rax
    mov rax, [rbp - 232]
    push rax
    mov rax, [rbp - 264]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 280], rax
    mov rax, [rbp - 280]
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global _start
_start:
    ; Initialize garbage collector runtime
    mov rdi, rsp
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    push rax         ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    pop rdi          ; Use main return as exit code
    mov rax, 60    ; sys_exit
    syscall
