; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 2 (AST_INLINE_ASM = 15)
; Declaration 1 type: 2 (AST_INLINE_ASM = 15)

global id_addr

id_addr:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    sub rsp, 80    ; Allocate 80 bytes on stack (aligned)
    ; Zero-initialize local variable space
    mov rdi, rsp  ; Destination for memset
    mov rax, 0     ; Value to set (zero)
    mov rcx, 80    ; Number of bytes
    rep stosb         ; Zero-fill the stack space
    ; Registering 1 function parameters
    mov [rbp - 8], rcx  ; Home param 'x'
    ; Parameter 'x' arrived in register rcx
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
ir_entry_0:
    lea rax, [rbp - 8]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    ; Store to variable: p
    mov [rbp - 16], rax  ; To stack [rbp - 16]
    ; Unary operation: *
    ; Load variable: p
    mov rax, [rbp - 16]  ; From stack [rbp - 16]
    mov eax, dword [rax]
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    jmp Lid_addr_exit
Lid_addr_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    sub rsp, 32    ; Allocate 32 bytes on stack (aligned)
    ; Zero-initialize local variable space
    mov rdi, rsp  ; Destination for memset
    mov rax, 0     ; Value to set (zero)
    mov rcx, 32    ; Number of bytes
    rep stosb         ; Zero-fill the stack space
    ; Registering 0 function parameters
    ; Added 8 bytes padding for 16-byte alignment
ir_entry_1:
    ; IR call: id_addr (1 args)
    sub rsp, 32      ; Allocate shadow space
    sub rsp, 8       ; Align stack to 16 bytes
    ; Save caller-saved registers (selective)
    push rax
    push r10
    push r11
    sub rsp, 16
    movdqu [rsp], xmm4  ; Save XMM4
    sub rsp, 16
    movdqu [rsp], xmm5  ; Save XMM5
    sub rsp, 16
    movdqu [rsp], xmm6  ; Save XMM6
    sub rsp, 16
    movdqu [rsp], xmm7  ; Save XMM7
    mov rax, 7
    mov rcx, rax
    call id_addr
    mov rcx, rax
    add rsp, 32
    add rsp, 8
    ; Restore caller-saved registers (selective)
    movdqu xmm7, [rsp]  ; Restore XMM7
    add rsp, 16
    movdqu xmm6, [rsp]  ; Restore XMM6
    add rsp, 16
    movdqu xmm5, [rsp]  ; Restore XMM5
    add rsp, 16
    movdqu xmm4, [rsp]  ; Restore XMM4
    add rsp, 16
    pop r11
    pop r10
    pop rax
    mov rax, rcx
    ; Integer/pointer return value in rax
    ; 32-bit return value already in eax
    mov [rbp - 8], rax
    mov rax, [rbp - 8]
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global _start
_start:
    ; Initialize garbage collector runtime
    mov rdi, rsp
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    push rax         ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    pop rdi          ; Use main return as exit code
    mov rax, 60    ; sys_exit
    syscall
