; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 2 (AST_INLINE_ASM = 15)

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    sub rsp, 224    ; Allocate 224 bytes on stack (aligned)
    ; Zero-initialize local variable space
    mov rdi, rsp  ; Destination for memset
    mov rax, 0     ; Value to set (zero)
    mov rcx, 224    ; Number of bytes
    rep stosb         ; Zero-fill the stack space
    ; Registering 0 function parameters
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
ir_entry_0:
    ; String literal: "Hello from string type!"
    lea rax, [Lstr_struct1 + rip]  ; Load string struct address
    ; Store to variable: msg
    mov [rbp - 16], rax  ; To stack [rbp - 16]
    lea rax, [rbp - 16]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, 8
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    mov rax, qword [rax]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    ; Store to variable: len
    mov [rbp - 24], rax  ; To stack [rbp - 24]
    lea rax, [rbp - 16]
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    push rax
    mov rax, 0
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    mov rax, qword [rax]
    mov [rbp - 136], rax
    mov rax, [rbp - 136]
    ; Store to variable: chrs
    mov [rbp - 40], rax  ; To stack [rbp - 40]
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global _start
_start:
    ; Initialize garbage collector runtime
    mov rdi, rsp
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    push rax         ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    pop rdi          ; Use main return as exit code
    mov rax, 60    ; sys_exit
    syscall
