; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 18)

section .text

global test

test:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 80    ; Allocate 80 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_0:
    mov rax, 5
    ; Store to variable: x
    mov dword [rbp - 4], eax  ; To stack [rbp - 4]
    ; Load variable: x
    mov eax, dword [rbp - 4]  ; From stack [rbp - 4]
    push rax
    mov rax, 1
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    test rax, rax
    jz ir_if_next_2
    mov rax, 2
    ; Store to variable: x
    mov dword [rbp - 4], eax  ; To stack [rbp - 4]
    jmp ir_if_end_1
ir_if_next_2:
    ; Load variable: x
    mov eax, dword [rbp - 4]  ; From stack [rbp - 4]
    push rax
    mov rax, 2
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    test rax, rax
    jz ir_if_next_3
    mov rax, 3
    ; Store to variable: x
    mov dword [rbp - 4], eax  ; To stack [rbp - 4]
    jmp ir_if_end_1
ir_if_next_3:
ir_if_end_1:
    mov rax, 0
    jmp Ltest_exit
Ltest_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    extern gc_shutdown
    call gc_shutdown
    mov rcx, 0       ; Default exit status
    extern ExitProcess
    call ExitProcess
