; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 20)
; Declaration 1 type: 4 (AST_INLINE_ASM = 20)

section .text

global cleanup

cleanup:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 32    ; Allocate 32 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_0:
    mov rax, 0
    mov [rbp - 8], rax
    mov rax, [rbp - 8]
    test rax, rax
    jz ir_errdefer_ok_1
    jmp ir_errdefer_end_2
ir_errdefer_ok_1:
ir_errdefer_end_2:
    jmp Lcleanup_exit
Lcleanup_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 48    ; Allocate 48 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_3:
    mov rax, 42
    mov [rbp - 8], rax
    mov rax, [rbp - 8]
    test rax, rax
    jz ir_errdefer_ok_4
    ; IR call: cleanup (0 args)
    sub rsp, 32
    call cleanup
    add rsp, 32
    ; Void return - no value to handle
    mov [rbp - 16], rax
    jmp ir_errdefer_end_5
ir_errdefer_ok_4:
ir_errdefer_end_5:
    mov rax, 42
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
