; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 21)

section .text
    extern system

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    extern gc_shutdown
    call gc_shutdown
    mov rcx, 0       ; Default exit status
    extern ExitProcess
    call ExitProcess
