; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 3 (AST_INLINE_ASM = 16)
; Declaration 1 type: 3 (AST_INLINE_ASM = 16)

global add

add:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    sub rsp, 48    ; Allocate 48 bytes on stack (aligned)
    ; Zero-initialize local variable space
    mov rdi, rsp  ; Destination for memset
    mov rax, 0     ; Value to set (zero)
    mov rcx, 48    ; Number of bytes
    rep stosb         ; Zero-fill the stack space
    ; Registering 2 function parameters
    mov [rbp - 8], rcx  ; Home param 'a'
    ; Parameter 'a' arrived in register rcx
    mov [rbp - 16], rdx  ; Home param 'b'
    ; Parameter 'b' arrived in register rdx
    ; Added 8 bytes padding for 16-byte alignment
ir_entry_0:
    ; Load variable: a
    mov rax, [rbp - 8]  ; From stack [rbp - 8]
    push rax
    ; Load variable: b
    mov rax, [rbp - 16]  ; From stack [rbp - 16]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    jmp Ladd_exit
Ladd_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    sub rsp, 48    ; Allocate 48 bytes on stack (aligned)
    ; Zero-initialize local variable space
    mov rdi, rsp  ; Destination for memset
    mov rax, 0     ; Value to set (zero)
    mov rcx, 48    ; Number of bytes
    rep stosb         ; Zero-fill the stack space
    ; Registering 0 function parameters
    ; Added 8 bytes padding for 16-byte alignment
    ; Added 8 bytes padding for 16-byte alignment
ir_entry_1:
    ; IR call: add (2 args)
    sub rsp, 32      ; Allocate shadow space
    sub rsp, 8       ; Align stack to 16 bytes
    ; Save caller-saved registers (selective)
    push rax
    push r10
    push r11
    sub rsp, 16
    movdqu [rsp], xmm4  ; Save XMM4
    sub rsp, 16
    movdqu [rsp], xmm5  ; Save XMM5
    sub rsp, 16
    movdqu [rsp], xmm6  ; Save XMM6
    sub rsp, 16
    movdqu [rsp], xmm7  ; Save XMM7
    mov rax, 10
    mov rcx, rax
    mov rax, 32
    mov rdx, rax
    call add
    mov rcx, rax
    add rsp, 32
    add rsp, 8
    ; Restore caller-saved registers (selective)
    movdqu xmm7, [rsp]  ; Restore XMM7
    add rsp, 16
    movdqu xmm6, [rsp]  ; Restore XMM6
    add rsp, 16
    movdqu xmm5, [rsp]  ; Restore XMM5
    add rsp, 16
    movdqu xmm4, [rsp]  ; Restore XMM4
    add rsp, 16
    pop r11
    pop r10
    pop rax
    mov rax, rcx
    ; Integer/pointer return value in rax
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    ; Store to variable: result
    mov [rbp - 8], rax  ; To stack [rbp - 8]
    ; Load variable: result
    mov rax, [rbp - 8]  ; From stack [rbp - 8]
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    mov rcx, rsp
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    push rax         ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    pop rcx          ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
