; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 20)
; Declaration 1 type: 5 (AST_INLINE_ASM = 20)

section .text

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 272    ; Allocate 272 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_0:
    lea rax, [rbp - 16]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    push rax
    mov rax, 8
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    mov rax, 3
    mov rcx, rax
    pop rax
    mov dword [rax], ecx
    lea rax, [rbp - 16]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    push rax
    mov rax, 12
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    push rax
    mov rax, 10
    mov rcx, rax
    pop rax
    mov dword [rax], ecx
    lea rax, [rbp - 16]
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    push rax
    mov rax, 8
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    mov eax, dword [rax]
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    test rax, rax
    jz ir_errdefer_ok_1
    jmp ir_errdefer_end_2
ir_errdefer_ok_1:
ir_errdefer_end_2:
    mov rax, [rbp - 88]
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller
    ; Struct declaration: List__int32
    ; Struct List__int32: size=16, alignment=8

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
