; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 4 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 21)
; Declaration 1 type: 4 (AST_INLINE_ASM = 21)
; Declaration 2 type: 4 (AST_INLINE_ASM = 21)
; Declaration 3 type: 4 (AST_INLINE_ASM = 21)

section .text
    extern masm_dir_exists
    extern masm_dir_create

global dir_exists

dir_exists:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 64    ; Allocate 64 bytes on stack (aligned)
    ; Registering 1 function parameters
    mov [rbp - 8], rcx  ; Home param 'path'
    ; Parameter 'path' arrived in register rcx
ir_entry_0:
    ; IR call: masm_dir_exists (1 args)
    sub rsp, 32
    ; Load variable: path
    mov rax, qword [rbp - 8]  ; From stack [rbp - 8]
    mov rcx, rax
    call masm_dir_exists
    add rsp, 32
    ; Integer/pointer return value in rax
    ; 32-bit return value already in eax
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    test rax, rax
    jz ir_errdefer_ok_1
    jmp ir_errdefer_end_2
ir_errdefer_ok_1:
ir_errdefer_end_2:
    mov rax, [rbp - 16]
    jmp Ldir_exists_exit
Ldir_exists_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global dir_create

dir_create:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 64    ; Allocate 64 bytes on stack (aligned)
    ; Registering 1 function parameters
    mov [rbp - 8], rcx  ; Home param 'path'
    ; Parameter 'path' arrived in register rcx
ir_entry_3:
    ; IR call: masm_dir_create (1 args)
    sub rsp, 32
    ; Load variable: path
    mov rax, qword [rbp - 8]  ; From stack [rbp - 8]
    mov rcx, rax
    call masm_dir_create
    add rsp, 32
    ; Integer/pointer return value in rax
    ; 32-bit return value already in eax
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    test rax, rax
    jz ir_errdefer_ok_4
    jmp ir_errdefer_end_5
ir_errdefer_ok_4:
ir_errdefer_end_5:
    mov rax, [rbp - 16]
    jmp Ldir_create_exit
Ldir_create_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    extern gc_shutdown
    call gc_shutdown
    mov rcx, 0       ; Default exit status
    extern ExitProcess
    call ExitProcess
