; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 18)

section .text

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 496    ; Allocate 496 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_0:
    mov rax, 128
    neg rax
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    ; Store to variable: a
    mov byte [rbp - 1], al  ; To stack [rbp - 1]
    mov rax, 127
    ; Store to variable: b
    mov byte [rbp - 2], al  ; To stack [rbp - 2]
    mov rax, 32768
    neg rax
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    ; Store to variable: c
    mov word [rbp - 4], ax  ; To stack [rbp - 4]
    mov rax, 2147483648
    neg rax
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    ; Store to variable: d
    mov dword [rbp - 8], eax  ; To stack [rbp - 8]
    mov rax, 1
    neg rax
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    ; Store to variable: e
    mov dword [rbp - 12], eax  ; To stack [rbp - 12]
    mov rax, 0
    push rax
    mov rax, 17
    mov r10, rax
    pop rax
    sub rax, r10
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    ; Store to variable: f
    mov dword [rbp - 16], eax  ; To stack [rbp - 16]
    mov rax, 0
    push rax
    ; Load variable: e
    movsxd rax, dword [rbp - 12]  ; From stack [rbp - 12]
    mov r10, rax
    pop rax
    sub rax, r10
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    ; Store to variable: g
    mov dword [rbp - 20], eax  ; To stack [rbp - 20]
    ; Load variable: a
    movsx rax, byte [rbp - 1]  ; From stack [rbp - 1] (signed)
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    setl al
    movzx rax, al
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    test rax, rax
    jz ir_sc_false_5
ir_sc_rhs_3:
    ; Load variable: b
    movsx rax, byte [rbp - 2]  ; From stack [rbp - 2] (signed)
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    setg al
    movzx rax, al
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    test rax, rax
    jz ir_sc_false_5
ir_sc_true_4:
    mov rax, 1
    mov [rbp - 96], rax
    jmp ir_sc_end_6
ir_sc_false_5:
    mov rax, 0
    mov [rbp - 96], rax
ir_sc_end_6:
    mov rax, [rbp - 96]
    test rax, rax
    jz ir_sc_false_9
ir_sc_rhs_7:
    ; Load variable: c
    movsx rax, word [rbp - 4]  ; From stack [rbp - 4] (signed)
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    setl al
    movzx rax, al
    mov [rbp - 112], rax
    mov rax, [rbp - 112]
    test rax, rax
    jz ir_sc_false_9
ir_sc_true_8:
    mov rax, 1
    mov [rbp - 120], rax
    jmp ir_sc_end_10
ir_sc_false_9:
    mov rax, 0
    mov [rbp - 120], rax
ir_sc_end_10:
    mov rax, [rbp - 120]
    test rax, rax
    jz ir_sc_false_13
ir_sc_rhs_11:
    ; Load variable: d
    movsxd rax, dword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    setl al
    movzx rax, al
    mov [rbp - 136], rax
    mov rax, [rbp - 136]
    test rax, rax
    jz ir_sc_false_13
ir_sc_true_12:
    mov rax, 1
    mov [rbp - 144], rax
    jmp ir_sc_end_14
ir_sc_false_13:
    mov rax, 0
    mov [rbp - 144], rax
ir_sc_end_14:
    mov rax, [rbp - 144]
    test rax, rax
    jz ir_if_next_2
    ; Load variable: g
    movsxd rax, dword [rbp - 20]  ; From stack [rbp - 20]
    jmp Lmain_exit
    jmp ir_if_end_1
ir_if_next_2:
ir_if_end_1:
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
