; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 18)

section .text

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 464    ; Allocate 464 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_0:
    mov rax, 7
    neg rax
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    ; Store to variable: a
    mov dword [rbp - 4], eax  ; To stack [rbp - 4]
    mov rax, 2
    ; Store to variable: b
    mov dword [rbp - 8], eax  ; To stack [rbp - 8]
    ; Load variable: a
    movsxd rax, dword [rbp - 4]  ; From stack [rbp - 4]
    push rax
    ; Load variable: b
    movsxd rax, dword [rbp - 8]  ; From stack [rbp - 8]
    mov r10, rax
    pop rax
    cqo
    idiv r10
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    ; Store to variable: q1
    mov dword [rbp - 12], eax  ; To stack [rbp - 12]
    mov rax, 0
    push rax
    mov rax, 2
    mov r10, rax
    pop rax
    sub rax, r10
    mov [rbp - 48], rax
    mov rax, 7
    push rax
    mov rax, [rbp - 48]
    mov r10, rax
    pop rax
    cqo
    idiv r10
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    ; Store to variable: q2
    mov dword [rbp - 16], eax  ; To stack [rbp - 16]
    mov rax, 0
    push rax
    mov rax, 9
    mov r10, rax
    pop rax
    sub rax, r10
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    push rax
    mov rax, 3
    mov r10, rax
    pop rax
    cqo
    idiv r10
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    ; Store to variable: q3
    mov dword [rbp - 20], eax  ; To stack [rbp - 20]
    mov rax, 0
    push rax
    mov rax, 3
    mov r10, rax
    pop rax
    sub rax, r10
    mov [rbp - 80], rax
    ; Load variable: q1
    movsxd rax, dword [rbp - 12]  ; From stack [rbp - 12]
    push rax
    mov rax, [rbp - 80]
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    test rax, rax
    jz ir_sc_false_5
ir_sc_rhs_3:
    mov rax, 0
    push rax
    mov rax, 3
    mov r10, rax
    pop rax
    sub rax, r10
    mov [rbp - 96], rax
    ; Load variable: q2
    movsxd rax, dword [rbp - 16]  ; From stack [rbp - 16]
    push rax
    mov rax, [rbp - 96]
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    test rax, rax
    jz ir_sc_false_5
ir_sc_true_4:
    mov rax, 1
    mov [rbp - 112], rax
    jmp ir_sc_end_6
ir_sc_false_5:
    mov rax, 0
    mov [rbp - 112], rax
ir_sc_end_6:
    mov rax, [rbp - 112]
    test rax, rax
    jz ir_sc_false_9
ir_sc_rhs_7:
    mov rax, 0
    push rax
    mov rax, 3
    mov r10, rax
    pop rax
    sub rax, r10
    mov [rbp - 128], rax
    ; Load variable: q3
    movsxd rax, dword [rbp - 20]  ; From stack [rbp - 20]
    push rax
    mov rax, [rbp - 128]
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 136], rax
    mov rax, [rbp - 136]
    test rax, rax
    jz ir_sc_false_9
ir_sc_true_8:
    mov rax, 1
    mov [rbp - 144], rax
    jmp ir_sc_end_10
ir_sc_false_9:
    mov rax, 0
    mov [rbp - 144], rax
ir_sc_end_10:
    mov rax, [rbp - 144]
    test rax, rax
    jz ir_if_next_2
    mov rax, 1
    jmp Lmain_exit
    jmp ir_if_end_1
ir_if_next_2:
ir_if_end_1:
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
