; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 3 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 18)
; Declaration 1 type: 4 (AST_INLINE_ASM = 18)
; Declaration 2 type: 4 (AST_INLINE_ASM = 18)

section .text

global widen_u8

widen_u8:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 16    ; Allocate 16 bytes on stack (aligned)
    ; Registering 1 function parameters
    mov [rbp - 8], rcx  ; Home param 'x'
    ; Parameter 'x' arrived in register rcx
ir_entry_0:
    ; Load variable: x
    movzx rax, byte [rbp - 8]  ; From stack [rbp - 8]
    jmp Lwiden_u8_exit
Lwiden_u8_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global widen_u16

widen_u16:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 16    ; Allocate 16 bytes on stack (aligned)
    ; Registering 1 function parameters
    mov [rbp - 8], rcx  ; Home param 'x'
    ; Parameter 'x' arrived in register rcx
ir_entry_1:
    ; Load variable: x
    movzx rax, word [rbp - 8]  ; From stack [rbp - 8]
    jmp Lwiden_u16_exit
Lwiden_u16_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 224    ; Allocate 224 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_2:
    mov rax, 255
    ; Store to variable: a
    mov byte [rbp - 1], al  ; To stack [rbp - 1]
    mov rax, 65535
    ; Store to variable: b
    mov word [rbp - 4], ax  ; To stack [rbp - 4]
    ; IR call: widen_u8 (1 args)
    sub rsp, 32
    ; Load variable: a
    movzx rax, byte [rbp - 1]  ; From stack [rbp - 1]
    mov rcx, rax
    call widen_u8
    mov rcx, rax
    add rsp, 32
    mov rax, rcx
    ; Integer/pointer return value in rax
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    ; Store to variable: x
    mov qword [rbp - 16], rax  ; To stack [rbp - 16]
    ; IR call: widen_u16 (1 args)
    sub rsp, 32
    ; Load variable: b
    movzx rax, word [rbp - 4]  ; From stack [rbp - 4]
    mov rcx, rax
    call widen_u16
    mov rcx, rax
    add rsp, 32
    mov rax, rcx
    ; Integer/pointer return value in rax
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    ; Store to variable: y
    mov qword [rbp - 24], rax  ; To stack [rbp - 24]
    ; Load variable: x
    mov rax, qword [rbp - 16]  ; From stack [rbp - 16]
    push rax
    mov rax, 255
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    test rax, rax
    jz ir_sc_false_7
ir_sc_rhs_5:
    ; Load variable: y
    mov rax, qword [rbp - 24]  ; From stack [rbp - 24]
    push rax
    mov rax, 65535
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    test rax, rax
    jz ir_sc_false_7
ir_sc_true_6:
    mov rax, 1
    mov [rbp - 64], rax
    jmp ir_sc_end_8
ir_sc_false_7:
    mov rax, 0
    mov [rbp - 64], rax
ir_sc_end_8:
    mov rax, [rbp - 64]
    test rax, rax
    jz ir_if_next_4
    mov rax, 1
    jmp Lmain_exit
    jmp ir_if_end_3
ir_if_next_4:
ir_if_end_3:
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
