; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 18)
; Declaration 1 type: 4 (AST_INLINE_ASM = 18)

section .text

global sum8

sum8:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 240    ; Allocate 240 bytes on stack (aligned)
    ; Registering 8 function parameters
    mov [rbp - 8], rcx  ; Home param 'a'
    ; Parameter 'a' arrived in register rcx
    mov [rbp - 16], rdx  ; Home param 'b'
    ; Parameter 'b' arrived in register rdx
    mov [rbp - 24], r8  ; Home param 'c'
    ; Parameter 'c' arrived in register r8
    mov [rbp - 32], r9  ; Home param 'd'
    ; Parameter 'd' arrived in register r9
    mov rax, [rbp + 48]  ; Load stack param 'e'
    mov [rbp - 40], rax  ; Home param 'e'
    ; Parameter 'e' arrived on stack [rbp + 48]
    mov rax, [rbp + 56]  ; Load stack param 'f'
    mov [rbp - 48], rax  ; Home param 'f'
    ; Parameter 'f' arrived on stack [rbp + 56]
    mov rax, [rbp + 64]  ; Load stack param 'g'
    mov [rbp - 56], rax  ; Home param 'g'
    ; Parameter 'g' arrived on stack [rbp + 64]
    mov rax, [rbp + 72]  ; Load stack param 'h'
    mov [rbp - 64], rax  ; Home param 'h'
    ; Parameter 'h' arrived on stack [rbp + 72]
ir_entry_0:
    ; Load variable: a
    movsxd rax, dword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    ; Load variable: b
    movsxd rax, dword [rbp - 16]  ; From stack [rbp - 16]
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    push rax
    ; Load variable: c
    movsxd rax, dword [rbp - 24]  ; From stack [rbp - 24]
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    push rax
    ; Load variable: d
    movsxd rax, dword [rbp - 32]  ; From stack [rbp - 32]
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    push rax
    ; Load variable: e
    movsxd rax, dword [rbp - 40]  ; From stack [rbp - 40]
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    push rax
    ; Load variable: f
    movsxd rax, dword [rbp - 48]  ; From stack [rbp - 48]
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    push rax
    ; Load variable: g
    movsxd rax, dword [rbp - 56]  ; From stack [rbp - 56]
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 112], rax
    mov rax, [rbp - 112]
    push rax
    ; Load variable: h
    movsxd rax, dword [rbp - 64]  ; From stack [rbp - 64]
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    jmp Lsum8_exit
Lsum8_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 32    ; Allocate 32 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_1:
    ; IR call: sum8 (8 args)
    sub rsp, 64
    mov rax, 5
    mov [rsp + 32], rax
    mov rax, 6
    mov [rsp + 40], rax
    mov rax, 7
    mov [rsp + 48], rax
    mov rax, 8
    mov [rsp + 56], rax
    mov rax, 1
    mov rcx, rax
    mov rax, 2
    mov rdx, rax
    mov rax, 3
    mov r8, rax
    mov rax, 4
    mov r9, rax
    call sum8
    mov rcx, rax
    add rsp, 64
    mov rax, rcx
    ; Integer/pointer return value in rax
    ; 32-bit return value already in eax
    mov [rbp - 8], rax
    mov rax, [rbp - 8]
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
