; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 18)

section .text

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 416    ; Allocate 416 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_0:
    mov rax, 1
    neg rax
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    ; Store to variable: a
    mov dword [rbp - 4], eax  ; To stack [rbp - 4]
    mov rax, 0
    ; Store to variable: b
    mov dword [rbp - 8], eax  ; To stack [rbp - 8]
    mov rax, 2
    neg rax
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    ; Store to variable: c
    mov dword [rbp - 12], eax  ; To stack [rbp - 12]
    mov rax, 32768
    neg rax
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    ; Store to variable: d
    mov word [rbp - 14], ax  ; To stack [rbp - 14]
    mov rax, 32767
    ; Store to variable: e
    mov word [rbp - 16], ax  ; To stack [rbp - 16]
    ; Load variable: a
    movsxd rax, dword [rbp - 4]  ; From stack [rbp - 4]
    push rax
    ; Load variable: b
    movsxd rax, dword [rbp - 8]  ; From stack [rbp - 8]
    mov r10, rax
    pop rax
    cmp rax, r10
    setl al
    movzx rax, al
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    test rax, rax
    jz ir_sc_false_5
ir_sc_rhs_3:
    ; Load variable: a
    movsxd rax, dword [rbp - 4]  ; From stack [rbp - 4]
    push rax
    ; Load variable: c
    movsxd rax, dword [rbp - 12]  ; From stack [rbp - 12]
    mov r10, rax
    pop rax
    cmp rax, r10
    setg al
    movzx rax, al
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    test rax, rax
    jz ir_sc_false_5
ir_sc_true_4:
    mov rax, 1
    mov [rbp - 64], rax
    jmp ir_sc_end_6
ir_sc_false_5:
    mov rax, 0
    mov [rbp - 64], rax
ir_sc_end_6:
    mov rax, [rbp - 64]
    test rax, rax
    jz ir_sc_false_9
ir_sc_rhs_7:
    ; Load variable: d
    movsx rax, word [rbp - 14]  ; From stack [rbp - 14] (signed)
    push rax
    ; Load variable: e
    movsx rax, word [rbp - 16]  ; From stack [rbp - 16] (signed)
    mov r10, rax
    pop rax
    cmp rax, r10
    setl al
    movzx rax, al
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    test rax, rax
    jz ir_sc_false_9
ir_sc_true_8:
    mov rax, 1
    mov [rbp - 88], rax
    jmp ir_sc_end_10
ir_sc_false_9:
    mov rax, 0
    mov [rbp - 88], rax
ir_sc_end_10:
    mov rax, [rbp - 88]
    test rax, rax
    jz ir_if_next_2
    ; Load variable: a
    movsxd rax, dword [rbp - 4]  ; From stack [rbp - 4]
    push rax
    ; Load variable: b
    movsxd rax, dword [rbp - 8]  ; From stack [rbp - 8]
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    test rax, rax
    jz ir_sc_false_15
ir_sc_rhs_13:
    ; Load variable: a
    movsxd rax, dword [rbp - 4]  ; From stack [rbp - 4]
    push rax
    ; Load variable: c
    movsxd rax, dword [rbp - 12]  ; From stack [rbp - 12]
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 112], rax
    mov rax, [rbp - 112]
    test rax, rax
    jz ir_sc_false_15
ir_sc_true_14:
    mov rax, 1
    mov [rbp - 120], rax
    jmp ir_sc_end_16
ir_sc_false_15:
    mov rax, 0
    mov [rbp - 120], rax
ir_sc_end_16:
    mov rax, [rbp - 120]
    test rax, rax
    jz ir_if_next_12
    mov rax, 1
    jmp Lmain_exit
    jmp ir_if_end_11
ir_if_next_12:
ir_if_end_11:
    jmp ir_if_end_1
ir_if_next_2:
ir_if_end_1:
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
