; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 3 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 18)
; Declaration 1 type: 4 (AST_INLINE_ASM = 18)
; Declaration 2 type: 4 (AST_INLINE_ASM = 18)

section .text

global take_u16

take_u16:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 16    ; Allocate 16 bytes on stack (aligned)
    ; Registering 1 function parameters
    mov [rbp - 8], rcx  ; Home param 'x'
    ; Parameter 'x' arrived in register rcx
ir_entry_0:
    ; Load variable: x
    movzx rax, word [rbp - 8]  ; From stack [rbp - 8]
    jmp Ltake_u16_exit
Ltake_u16_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global take_i16

take_i16:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 16    ; Allocate 16 bytes on stack (aligned)
    ; Registering 1 function parameters
    mov [rbp - 8], rcx  ; Home param 'x'
    ; Parameter 'x' arrived in register rcx
ir_entry_1:
    ; Load variable: x
    movsx rax, word [rbp - 8]  ; From stack [rbp - 8] (signed)
    jmp Ltake_i16_exit
Ltake_i16_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 256    ; Allocate 256 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_2:
    mov rax, 255
    ; Store to variable: u8
    mov byte [rbp - 1], al  ; To stack [rbp - 1]
    mov rax, 1
    neg rax
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    ; Store to variable: i8
    mov byte [rbp - 2], al  ; To stack [rbp - 2]
    ; IR call: take_u16 (1 args)
    sub rsp, 32
    ; Load variable: u8
    movzx rax, byte [rbp - 1]  ; From stack [rbp - 1]
    mov rcx, rax
    call take_u16
    mov rcx, rax
    add rsp, 32
    mov rax, rcx
    ; Integer/pointer return value in rax
    ; 32-bit return value already in eax
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    ; Store to variable: u16
    mov word [rbp - 4], ax  ; To stack [rbp - 4]
    ; IR call: take_i16 (1 args)
    sub rsp, 32
    ; Load variable: i8
    movsx rax, byte [rbp - 2]  ; From stack [rbp - 2] (signed)
    mov rcx, rax
    call take_i16
    mov rcx, rax
    add rsp, 32
    mov rax, rcx
    ; Integer/pointer return value in rax
    ; 32-bit return value already in eax
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    ; Store to variable: i16
    mov word [rbp - 6], ax  ; To stack [rbp - 6]
    ; Load variable: u16
    movzx rax, word [rbp - 4]  ; From stack [rbp - 4]
    push rax
    mov rax, 255
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    test rax, rax
    jz ir_sc_false_7
ir_sc_rhs_5:
    mov rax, 1
    neg rax
    mov [rbp - 48], rax
    ; Load variable: i16
    movsx rax, word [rbp - 6]  ; From stack [rbp - 6] (signed)
    push rax
    mov rax, [rbp - 48]
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    test rax, rax
    jz ir_sc_false_7
ir_sc_true_6:
    mov rax, 1
    mov [rbp - 64], rax
    jmp ir_sc_end_8
ir_sc_false_7:
    mov rax, 0
    mov [rbp - 64], rax
ir_sc_end_8:
    mov rax, [rbp - 64]
    test rax, rax
    jz ir_if_next_4
    mov rax, 1
    jmp Lmain_exit
    jmp ir_if_end_3
ir_if_next_4:
ir_if_end_3:
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
