; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 6 (AST_INLINE_ASM = 18)
; Declaration 1 type: 4 (AST_INLINE_ASM = 18)

section .text

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 208    ; Allocate 208 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_0:
    mov rax, 0
    ; Store to variable: a
    mov qword [rbp - 8], rax  ; To stack [rbp - 8]
    mov rax, 2
    ; Store to variable: b
    mov qword [rbp - 16], rax  ; To stack [rbp - 16]
    mov rax, 3
    ; Store to variable: c
    mov qword [rbp - 24], rax  ; To stack [rbp - 24]
    mov rax, -5
    ; Store to variable: d
    mov qword [rbp - 32], rax  ; To stack [rbp - 32]
    ; Load variable: a
    mov rax, qword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    test rax, rax
    jz ir_if_else_1
    mov rax, 1
    jmp Lmain_exit
    jmp ir_if_end_2
ir_if_else_1:
ir_if_end_2:
    ; Load variable: b
    mov rax, qword [rbp - 16]  ; From stack [rbp - 16]
    push rax
    mov rax, 2
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    test rax, rax
    jz ir_if_else_3
    mov rax, 2
    jmp Lmain_exit
    jmp ir_if_end_4
ir_if_else_3:
ir_if_end_4:
    ; Load variable: c
    mov rax, qword [rbp - 24]  ; From stack [rbp - 24]
    push rax
    mov rax, 3
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    test rax, rax
    jz ir_if_else_5
    mov rax, 3
    jmp Lmain_exit
    jmp ir_if_end_6
ir_if_else_5:
ir_if_end_6:
    mov rax, 5
    neg rax
    mov [rbp - 64], rax
    ; Load variable: d
    mov rax, qword [rbp - 32]  ; From stack [rbp - 32]
    push rax
    mov rax, [rbp - 64]
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    test rax, rax
    jz ir_if_else_7
    mov rax, 4
    jmp Lmain_exit
    jmp ir_if_end_8
ir_if_else_7:
ir_if_end_8:
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
