; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 18)

section .text

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 272    ; Allocate 272 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_0:
    mov rax, 127
    ; Store to variable: a
    mov byte [rbp - 1], al  ; To stack [rbp - 1]
    mov rax, 1
    ; Store to variable: b
    mov byte [rbp - 2], al  ; To stack [rbp - 2]
    ; Load variable: a
    movsx rax, byte [rbp - 1]  ; From stack [rbp - 1] (signed)
    push rax
    ; Load variable: b
    movsx rax, byte [rbp - 2]  ; From stack [rbp - 2] (signed)
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    ; Store to variable: c
    mov byte [rbp - 3], al  ; To stack [rbp - 3]
    mov rax, 128
    neg rax
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    ; Store to variable: d
    mov byte [rbp - 4], al  ; To stack [rbp - 4]
    ; Load variable: d
    movsx rax, byte [rbp - 4]  ; From stack [rbp - 4] (signed)
    push rax
    mov rax, 1
    mov r10, rax
    pop rax
    sub rax, r10
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    ; Store to variable: e
    mov byte [rbp - 5], al  ; To stack [rbp - 5]
    mov rax, 128
    neg rax
    mov [rbp - 40], rax
    ; Load variable: c
    movsx rax, byte [rbp - 3]  ; From stack [rbp - 3] (signed)
    push rax
    mov rax, [rbp - 40]
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    test rax, rax
    jz ir_sc_false_5
ir_sc_rhs_3:
    ; Load variable: e
    movsx rax, byte [rbp - 5]  ; From stack [rbp - 5] (signed)
    push rax
    mov rax, 127
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    test rax, rax
    jz ir_sc_false_5
ir_sc_true_4:
    mov rax, 1
    mov [rbp - 64], rax
    jmp ir_sc_end_6
ir_sc_false_5:
    mov rax, 0
    mov [rbp - 64], rax
ir_sc_end_6:
    mov rax, [rbp - 64]
    test rax, rax
    jz ir_if_next_2
    mov rax, 1
    jmp Lmain_exit
    jmp ir_if_end_1
ir_if_next_2:
ir_if_end_1:
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
