; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 20)

section .text

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 560    ; Allocate 560 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_0:
    mov rax, 0
    test rax, rax
    setz al
    movzx rax, al
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    ; Store to variable: a
    mov dword [rbp - 4], eax  ; To stack [rbp - 4]
    ; Load variable: a
    movsxd rax, dword [rbp - 4]  ; From stack [rbp - 4]
    push rax
    mov rax, 1
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    test rax, rax
    jz ir_if_next_2
    mov rax, 1
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    test rax, rax
    jz ir_errdefer_ok_3
    jmp ir_errdefer_end_4
ir_errdefer_ok_3:
ir_errdefer_end_4:
    mov rax, 1
    jmp Lmain_exit
    jmp ir_if_end_1
ir_if_next_2:
ir_if_end_1:
    mov rax, 1
    test rax, rax
    setz al
    movzx rax, al
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    ; Store to variable: b
    mov dword [rbp - 8], eax  ; To stack [rbp - 8]
    ; Load variable: b
    movsxd rax, dword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    test rax, rax
    jz ir_if_next_6
    mov rax, 2
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    test rax, rax
    jz ir_errdefer_ok_7
    jmp ir_errdefer_end_8
ir_errdefer_ok_7:
ir_errdefer_end_8:
    mov rax, 2
    jmp Lmain_exit
    jmp ir_if_end_5
ir_if_next_6:
ir_if_end_5:
    mov rax, 42
    test rax, rax
    setz al
    movzx rax, al
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    ; Store to variable: c
    mov dword [rbp - 12], eax  ; To stack [rbp - 12]
    ; Load variable: c
    movsxd rax, dword [rbp - 12]  ; From stack [rbp - 12]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    test rax, rax
    jz ir_if_next_10
    mov rax, 3
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    test rax, rax
    jz ir_errdefer_ok_11
    jmp ir_errdefer_end_12
ir_errdefer_ok_11:
ir_errdefer_end_12:
    mov rax, 3
    jmp Lmain_exit
    jmp ir_if_end_9
ir_if_next_10:
ir_if_end_9:
    mov rax, 5
    test rax, rax
    setz al
    movzx rax, al
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    test rax, rax
    setz al
    movzx rax, al
    mov [rbp - 112], rax
    mov rax, [rbp - 112]
    ; Store to variable: d
    mov dword [rbp - 16], eax  ; To stack [rbp - 16]
    ; Load variable: d
    movsxd rax, dword [rbp - 16]  ; From stack [rbp - 16]
    push rax
    mov rax, 1
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    test rax, rax
    jz ir_if_next_14
    mov rax, 4
    mov [rbp - 128], rax
    mov rax, [rbp - 128]
    test rax, rax
    jz ir_errdefer_ok_15
    jmp ir_errdefer_end_16
ir_errdefer_ok_15:
ir_errdefer_end_16:
    mov rax, 4
    jmp Lmain_exit
    jmp ir_if_end_13
ir_if_next_14:
ir_if_end_13:
    mov rax, 0
    ; Store to variable: x
    mov dword [rbp - 20], eax  ; To stack [rbp - 20]
    ; Load variable: x
    movsxd rax, dword [rbp - 20]  ; From stack [rbp - 20]
    test rax, rax
    setz al
    movzx rax, al
    mov [rbp - 136], rax
    mov rax, [rbp - 136]
    test rax, rax
    jz ir_if_next_18
    mov rax, 10
    ; Store to variable: x
    mov dword [rbp - 20], eax  ; To stack [rbp - 20]
    jmp ir_if_end_17
ir_if_next_18:
ir_if_end_17:
    ; Load variable: x
    movsxd rax, dword [rbp - 20]  ; From stack [rbp - 20]
    push rax
    mov rax, 10
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 144], rax
    mov rax, [rbp - 144]
    test rax, rax
    jz ir_if_next_20
    mov rax, 5
    mov [rbp - 152], rax
    mov rax, [rbp - 152]
    test rax, rax
    jz ir_errdefer_ok_21
    jmp ir_errdefer_end_22
ir_errdefer_ok_21:
ir_errdefer_end_22:
    mov rax, 5
    jmp Lmain_exit
    jmp ir_if_end_19
ir_if_next_20:
ir_if_end_19:
    mov rax, 7
    ; Store to variable: y
    mov dword [rbp - 24], eax  ; To stack [rbp - 24]
    ; Load variable: y
    movsxd rax, dword [rbp - 24]  ; From stack [rbp - 24]
    test rax, rax
    setz al
    movzx rax, al
    mov [rbp - 160], rax
    mov rax, [rbp - 160]
    test rax, rax
    jz ir_if_next_24
    mov rax, 6
    mov [rbp - 168], rax
    mov rax, [rbp - 168]
    test rax, rax
    jz ir_errdefer_ok_25
    jmp ir_errdefer_end_26
ir_errdefer_ok_25:
ir_errdefer_end_26:
    mov rax, 6
    jmp Lmain_exit
    jmp ir_if_end_23
ir_if_next_24:
ir_if_end_23:
    mov rax, 0
    mov [rbp - 176], rax
    mov rax, [rbp - 176]
    test rax, rax
    jz ir_errdefer_ok_27
    jmp ir_errdefer_end_28
ir_errdefer_ok_27:
ir_errdefer_end_28:
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
