; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 3 declarations
; Declaration 0 type: 5 (AST_INLINE_ASM = 18)
; Declaration 1 type: 4 (AST_INLINE_ASM = 18)
; Declaration 2 type: 4 (AST_INLINE_ASM = 18)

section .text
    ; Struct declaration: Pair
    ; Struct Pair: size=8, alignment=4

global sum_pair

sum_pair:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 128    ; Allocate 128 bytes on stack (aligned)
    ; Registering 1 function parameters
    mov [rbp - 8], rcx  ; Home param 'p'
    ; Parameter 'p' arrived in register rcx
ir_entry_0:
    ; Load variable: p
    mov rax, qword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 16], rax
    mov rax, [rbp - 16]
    mov eax, dword [rax]
    mov [rbp - 24], rax
    ; Load variable: p
    mov rax, qword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 4
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    mov eax, dword [rax]
    mov [rbp - 40], rax
    mov rax, [rbp - 24]
    push rax
    mov rax, [rbp - 40]
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    jmp Lsum_pair_exit
Lsum_pair_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 304    ; Allocate 304 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_1:
    ; IR new: Pair (8 bytes)
    mov rcx, 8
    extern gc_alloc
    call gc_alloc
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    ; Store to variable: p
    mov qword [rbp - 8], rax  ; To stack [rbp - 8]
    ; Load variable: p
    mov rax, qword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    push rax
    mov rax, 7
    mov rcx, rax
    pop rax
    mov dword [rax], ecx
    ; Load variable: p
    mov rax, qword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 4
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    push rax
    mov rax, 9
    mov rcx, rax
    pop rax
    mov dword [rax], ecx
    ; Load variable: p
    mov rax, qword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    ; Store to variable: pa
    mov qword [rbp - 16], rax  ; To stack [rbp - 16]
    ; Load variable: pa
    mov rax, qword [rbp - 16]  ; From stack [rbp - 16]
    mov eax, dword [rax]
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    push rax
    mov rax, 5
    mov r10, rax
    pop rax
    add rax, r10
    mov [rbp - 80], rax
    ; Load variable: pa
    mov rax, qword [rbp - 16]  ; From stack [rbp - 16]
    push rax
    mov rax, [rbp - 80]
    mov rcx, rax
    pop rax
    mov dword [rax], ecx
    ; Load variable: pa
    mov rax, qword [rbp - 16]  ; From stack [rbp - 16]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    test rax, rax
    jz ir_if_else_2
    mov rax, 1
    jmp Lmain_exit
    jmp ir_if_end_3
ir_if_else_2:
ir_if_end_3:
    ; Load variable: p
    mov rax, qword [rbp - 8]  ; From stack [rbp - 8]
    push rax
    mov rax, 0
    mov r10, rax
    pop rax
    cmp rax, r10
    setne al
    movzx rax, al
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    test rax, rax
    jz ir_if_else_4
    ; IR call: sum_pair (1 args)
    sub rsp, 32
    ; Load variable: p
    mov rax, qword [rbp - 8]  ; From stack [rbp - 8]
    mov rcx, rax
    call sum_pair
    mov rcx, rax
    add rsp, 32
    mov rax, rcx
    ; Integer/pointer return value in rax
    ; 32-bit return value already in eax
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    jmp Lmain_exit
    jmp ir_if_end_5
ir_if_else_4:
ir_if_end_5:
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
