; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 3 declarations
; Declaration 0 type: 4 (AST_INLINE_ASM = 18)
; Declaration 1 type: 4 (AST_INLINE_ASM = 18)
; Declaration 2 type: 4 (AST_INLINE_ASM = 18)

section .text

global widen_i8

widen_i8:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 16    ; Allocate 16 bytes on stack (aligned)
    ; Registering 1 function parameters
    mov [rbp - 8], rcx  ; Home param 'x'
    ; Parameter 'x' arrived in register rcx
ir_entry_0:
    ; Load variable: x
    movsx rax, byte [rbp - 8]  ; From stack [rbp - 8] (signed)
    jmp Lwiden_i8_exit
Lwiden_i8_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global widen_i16

widen_i16:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 16    ; Allocate 16 bytes on stack (aligned)
    ; Registering 1 function parameters
    mov [rbp - 8], rcx  ; Home param 'x'
    ; Parameter 'x' arrived in register rcx
ir_entry_1:
    ; Load variable: x
    movsx rax, word [rbp - 8]  ; From stack [rbp - 8] (signed)
    jmp Lwiden_i16_exit
Lwiden_i16_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    sub rsp, 496    ; Allocate 496 bytes on stack (aligned)
    ; Registering 0 function parameters
ir_entry_2:
    mov rax, 1
    neg rax
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    ; Store to variable: a
    mov byte [rbp - 1], al  ; To stack [rbp - 1]
    mov rax, 128
    neg rax
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    ; Store to variable: b
    mov byte [rbp - 2], al  ; To stack [rbp - 2]
    mov rax, 32768
    neg rax
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    ; Store to variable: c
    mov word [rbp - 4], ax  ; To stack [rbp - 4]
    ; IR call: widen_i8 (1 args)
    sub rsp, 32
    ; Load variable: a
    movsx rax, byte [rbp - 1]  ; From stack [rbp - 1] (signed)
    mov rcx, rax
    call widen_i8
    mov rcx, rax
    add rsp, 32
    mov rax, rcx
    ; Integer/pointer return value in rax
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    ; Store to variable: x
    mov qword [rbp - 16], rax  ; To stack [rbp - 16]
    ; IR call: widen_i8 (1 args)
    sub rsp, 32
    ; Load variable: b
    movsx rax, byte [rbp - 2]  ; From stack [rbp - 2] (signed)
    mov rcx, rax
    call widen_i8
    mov rcx, rax
    add rsp, 32
    mov rax, rcx
    ; Integer/pointer return value in rax
    mov [rbp - 72], rax
    mov rax, [rbp - 72]
    ; Store to variable: y
    mov qword [rbp - 24], rax  ; To stack [rbp - 24]
    ; IR call: widen_i16 (1 args)
    sub rsp, 32
    ; Load variable: c
    movsx rax, word [rbp - 4]  ; From stack [rbp - 4] (signed)
    mov rcx, rax
    call widen_i16
    mov rcx, rax
    add rsp, 32
    mov rax, rcx
    ; Integer/pointer return value in rax
    mov [rbp - 80], rax
    mov rax, [rbp - 80]
    ; Store to variable: z
    mov qword [rbp - 32], rax  ; To stack [rbp - 32]
    mov rax, 1
    neg rax
    mov [rbp - 88], rax
    ; Load variable: x
    mov rax, qword [rbp - 16]  ; From stack [rbp - 16]
    push rax
    mov rax, [rbp - 88]
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    test rax, rax
    jz ir_sc_false_7
ir_sc_rhs_5:
    mov rax, 128
    neg rax
    mov [rbp - 104], rax
    ; Load variable: y
    mov rax, qword [rbp - 24]  ; From stack [rbp - 24]
    push rax
    mov rax, [rbp - 104]
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 112], rax
    mov rax, [rbp - 112]
    test rax, rax
    jz ir_sc_false_7
ir_sc_true_6:
    mov rax, 1
    mov [rbp - 120], rax
    jmp ir_sc_end_8
ir_sc_false_7:
    mov rax, 0
    mov [rbp - 120], rax
ir_sc_end_8:
    mov rax, [rbp - 120]
    test rax, rax
    jz ir_sc_false_11
ir_sc_rhs_9:
    mov rax, 32768
    neg rax
    mov [rbp - 136], rax
    ; Load variable: z
    mov rax, qword [rbp - 32]  ; From stack [rbp - 32]
    push rax
    mov rax, [rbp - 136]
    mov r10, rax
    pop rax
    cmp rax, r10
    sete al
    movzx rax, al
    mov [rbp - 144], rax
    mov rax, [rbp - 144]
    test rax, rax
    jz ir_sc_false_11
ir_sc_true_10:
    mov rax, 1
    mov [rbp - 152], rax
    jmp ir_sc_end_12
ir_sc_false_11:
    mov rax, 0
    mov [rbp - 152], rax
ir_sc_end_12:
    mov rax, [rbp - 152]
    test rax, rax
    jz ir_if_next_4
    mov rax, 1
    jmp Lmain_exit
    jmp ir_if_end_3
ir_if_next_4:
ir_if_end_3:
    mov rax, 0
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global mainCRTStartup
mainCRTStartup:
    sub rsp, 40      ; Shadow space + alignment
    ; Initialize garbage collector runtime
    lea rcx, [rsp + 40]
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    mov [rsp + 32], rax ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    mov rcx, [rsp + 32] ; Use main return as exit code
    extern ExitProcess
    call ExitProcess
